---
title: "rhetoric"
format: html
editor: visual
bibliography: references.bib
---

## Arguments in Missing Data Assumptions

The overall argument that author takes is discussing the basis of how to analyze data when you have missing values. The author talks about having many options and using the one that best fits the scenario and the type of analysis that you will be doing as a statistician. I think understanding where the author is coming from really helps the reader. We know the author and Ruben contributed to this field very heavily and these methods are brought together as a synopsis of a field. This allows us to grasp the concepts that the author is discussing and to put his arguments into context.

The author throughout his paper does not take many strong stances on a lot of methods or assumptions. This paper's purpose is to look at the methods and state assumptions along with some practicality of the methods. Understanding this point we can look at the first section of the paper and how maximum likelihood estimation is used along with Bayesian statistics. In this section we see the author petition for using these methods in missing data estimation. The author discusses how and when to use these methods.

Throughout the paper we also see the author take a stronger stance on what methods not to use such as pure replacement and deletion. This stance shows the purpose of this paper in reviewing methods of missing data estimation from method experts. We see the intention of the author to discuss methods that are most commonly used incorrectly. This point allows the author to give his opinion without hindering his voice on the methods that he is mainly talking about in his paper.

Finally we also see the author come together and make comment on his position on non - MLE methods of missing data estimation. These sections allow the author time to discuss methods that are not commonly discussed in other papers as well as hint at some things he and Ruben have developed. We then learn how to understand the way this author thinks and how he constructs arguments throughout the paper. The way the author constructs his arguments are most of the time subtle, which fit the style of this paper as it is a article reviewing methods of missing data estimation. This allows the author to make arguments along with commenting on methods and processes in the field.

References

@littleMissingDataAssumptions2021
